## Chrurn Prediction using ANN

### Importing Libraries 

In [54]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
import tensorflow as tf 

### Data Preprocessing

Importing data 

In [55]:
tf.__version__
# get the version of tensorflow 

'2.12.0'

In [56]:
df = pd.read_csv("Churn_Modelling.csv")

In [57]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [58]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [59]:
# skip rownumber, customerID, and surname.
X = df.iloc[:, 3:-1]
Y = df.iloc[:, -1]

In [60]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [61]:
Y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

Encoding the categorical data - Gender and Geography 

In [62]:
# encoding gender 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X.iloc[:, 2] = le.fit_transform(X.iloc[:, 2])

C:\Users\Antriksh\AppData\Local\Temp\ipykernel_30936\862313144.py:4: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  X.iloc[:, 2] = le.fit_transform(X.iloc[:, 2])


In [63]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

One - Hot Encoding of Geography Data 

In [67]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = ct.fit_transform(X)
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

 Splitting the dataset into test and train

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15, random_state=20113030)

Feature Scaling

In [69]:
# Normal Distribution
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Building an ANN

In [70]:
ann = tf.keras.models.Sequential()
# !pip install --upgrade tensorflow

In [71]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

In [72]:
ann.add(tf.keras.layers.Dense(units=16, activation='relu'))

In [73]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# sigmoid states the probabilities of leaving and non-leaving

### Training

In [74]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics= ['accuracy'])

In [75]:
ann.fit(X_train, Y_train, batch_size= 32, epochs=100)
# Batch_size parameter specifies the number of samples from 
# the training dataset that will be used in each update of the model's parameters

Epoch 1/100
266/266 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7208
Epoch 2/100
266/266 [==============================] - 0s 2ms/step - loss: 0.4554 - accuracy: 0.7972
Epoch 3/100
266/266 [==============================] - 0s 2ms/step - loss: 0.4323 - accuracy: 0.8012
Epoch 4/100
266/266 [==============================] - 1s 2ms/step - loss: 0.4075 - accuracy: 0.8169
Epoch 5/100
266/266 [==============================] - 0s 2ms/step - loss: 0.3829 - accuracy: 0.8387
Epoch 6/100
266/266 [==============================] - 0s 2ms/step - loss: 0.3683 - accuracy: 0.8496
Epoch 7/100
266/266 [==============================] - 0s 2ms/step - loss: 0.3596 - accuracy: 0.8538
Epoch 8/100
266/266 [==============================] - 0s 2ms/step - loss: 0.3542 - accuracy: 0.8562
Epoch 9/100
266/266 [==============================] - 0s 2ms/step - loss: 0.3501 - accuracy: 0.8574
Epoch 10/100
266/266 [==============================] - 1s 2ms/step - loss: 0.3472 - accura

### Evaluation

In [82]:
Y_pred = ann.predict(X_test)
Y_pred = np.where(Y_pred > 0.5, 1, 0)
Y_pred      

47/47 [==============================] - 0s 2ms/step


array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [84]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(accuracy_score(Y_test, Y_pred))
print(cm)

0.862
[[1141   51]
 [ 156  152]]


### Prediction 
for --

Customer Name - Antriksh || ID = 189908876 || Geography = France || Credit Score = 700 || Gender = Male || Age = 21 || Tenure = 2 years || Balance = 10000 || Number of Products = 1 || Credit Card = 1 || Active Member = 1 || Salary = 12000 

In [77]:
if ann.predict(sc.transform([[1, 0, 0, 700, 1, 21, 2, 10000, 1, 1, 1, 12000]])) > 0.5:
    print("Will leave the bank")
else:
    print("Will not leave the bank")    

1/1 [==============================] - 0s 53ms/step
Will not leave the bank


In [ ]:
#  will not leave the bank.